---
# Remove the autostart function from ~/.profile if it exists
- name: Remove the autostart command from ~/.profile if it exists
  file: 
    dest: ~/.config/autostart/ansible.desktop 
    state: absent 

- name: Remove the 'Remove Config' Line from config.yml
  lineinfile:
    dest: "{{ playbook_dir }}/config.yml"
    state: absent
    regexp: "remove_autostart: true"